attentive-mobile/attentive-ios-sdk

Example/Example.xcodeproj/project.pbxproj
Example/Example/ViewController.m

add file references to local sdk in Example project

file references to local sdk in example

---

attentive-ios-sdk.podspec

- update git repo link to use https
- update version to 0.1.1

update git repo link to use https

---

.gitignore
Creative/ATTNSDK.m
Example/Example.xcodeproj/project.pbxproj
Example/Example/ViewController.m
attentive-ios-sdk.podspec

- make webview transparent to work with floating creatives
- make example background grey to show the transparency
- update to v0.1.2 for new release

transparent webview

---

Sources/ATTNSDK.m

- add identifiers to creatives call
- isEqual --> isEqualToString
- fix success log in debug mode

add identifiers to creatives call

---

Example/Example/ViewController.m
Sources/ATTNParameterValidation.h
Sources/ATTNParameterValidation.m
Sources/ATTNUserIdentity.h
Tests/ATTNAPITest.m
Tests/ATTNParameterValidationTest.m
Tests/ATTNPersistentStorageTest.m
Tests/ATTNUserIdentityTest.m
Tests/ATTNVisitorServiceTest.m
attentive-ios-sdk.xcodeproj/project.pbxproj

Adds iOS unit tests for multiple classes

Adds iOS unit tests

---

ATTNTestEventUtils.h
Sources/ATTNAPI.h
Sources/ATTNAPI.m
Tests/ATTNAPITest.m
Tests/ATTNAPITestIT.m
Tests/ATTNTestEventUtils.m
attentive-ios-sdk.xcodeproj/project.pbxproj

- integration tests for sending events
- add callbacks for event sending methods for ease of testing
- move some common methods from ATTNAPITest to ATTNTestEventUtils

integration tests

---

ATTNTestEventUtils.h
Example/Base.lproj/Main.storyboard
Example/Example/ProductViewController.h
Example/Example/ProductViewController.m
ExampleSwift/Base.lproj/Main.storyboard
ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj
ExampleSwift/ExampleSwift/ProductViewController.swift
ExampleSwift/ExampleSwift/attentive-ios-sdk-bridging-header.h
ExampleSwift/ExampleSwift/attentive-ios-sdk-local-bridging-header.h
Framework/ATTNSDKFramework.h
Sources/ATTNAPI.m
Sources/ATTNCustomEvent.h
Sources/ATTNCustomEvent.m
Tests/ATTNAPITest.m
Tests/ATTNAPITestIT.m
Tests/ATTNTestEventUtils.m
attentive-ios-sdk.xcodeproj/project.pbxproj

* Adds CustomEvent
* Example apps are updated to send CustomEvent from the product page

Adds Custom Events

---

Sources/Internal/ATTNVersion.h
attentive-ios-sdk.podspec

Version bump to release regex fix for more accurate and robust dtag parsing.

Update version to release regex change

---

Sources/ATTNSDK.m
Tests/ATTNAPITestIT.m

Log version `v0.4.3-beta.0`
This is to start testing pre-release versions and its publishing flow.

feat: log sdk version on init

---

Sources/Internal/ATTNVersion.h
attentive-ios-sdk.podspec

No new features, just releases all beta changes within 0.4.3-beta.1 and 0.4.3-beta.2 now that we have confirmed proper behavior

0.4.3 release

---

README.md

[Jira Link](https://attentivemobile.atlassian.net/browse/APP-2976)
- README now has implementation examples with Swift

[APP-2976] Update documentation to make `identify` signature more clear

---

CHANGELOG.md
README.md
Sources/Internal/ATTNVersion.h
attentive-ios-sdk.podspec

- Bumped Version to 0.5.1
- Added CHANGELOG.md

Release Version 0.5.1

---

ATTNSDKFramework.podspec
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

Publish Beta for 0.6.0

---

ATTNSDKFramework.podspec
CHANGELOG.md
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

* Bumped Version to 0.6.0
* Updated CHANGELOG.md

Release Version 0.6.0

---

Example/Base.lproj/Main.storyboard
Example/CreativeUITest/CreativeUITest.swift
Example/CreativeUITest/Pages/HomePage.swift
Example/CreativeUITest/Pages/Page.swift
Example/CreativeUITest/Pages/SwitchDomainPage.swift
Example/Example.xcodeproj/project.pbxproj
Example/Example/ViewController.m
ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj
ExampleSwift/ExampleSwift/AppDelegate.swift
ExampleSwift/ExampleSwift/ProductViewController.swift
README.md
Sources/API/ATTNAPI.swift
Sources/API/ATTNAPIProtocol.swift
Sources/Public/ATTNEventTracker.swift
Sources/Public/SDK/ATTNSDK.swift
Tests/Doubles/Spies/ATTNAPISpy.swift
Tests/Doubles/Spies/ATTNCreativeUrlProviderSpy.swift
Tests/TestCases/ATTNSDKTests.swift
attentive-ios-sdk.xcodeproj/project.pbxproj
attentive-ios-sdk.xcworkspace/xcshareddata/swiftpm/Package.resolved

[Jira Link](https://attentivemobile.atlassian.net/browse/APP-2804)
Added a new way to update the SDK domain.
```swift
let sdk = ATTNSDK(domain: "oldDomain")
sdk.update(domain: "newDomain")
```
* Added unit test to cover new public method
* Added one UI Automation Test Case
https://github.com/attentive-mobile/attentive-ios-sdk/assets/11541905/0242372e-a4f7-4372-9ffe-619694279245

[APP-2804] Mobile App Domain Switching - iOS

---

Example/CreativeUITest/CreativeUITest.swift
Example/CreativeUITest/Extensions/XCUIElement+Extension.swift
Example/CreativeUITest/Pages/CreativePage.swift
Example/CreativeUITest/Pages/HomePage.swift
Example/CreativeUITest/Pages/SMSPage.swift
Example/CreativeUITest/Protocols/BaseXCTestCase.swift
Example/Example.xcodeproj/xcshareddata/xcschemes/CreativeUITest.xcscheme

[Jira Link](https://attentivemobile.atlassian.net/browse/APP-2876)
Removed the deleteApp method due to issues with AWS's signing capability.
https://us-west-2.console.aws.amazon.com/devicefarm/home#/mobile/projects/f4548306-b9e8-4c6e-84d1-cec59b44c35e/runs/65546f80-19ea-4039-a826-422c70c152e0

[APP-2876] Create (or update) test suite - Fixes

---

ATTNSDKFramework.podspec
CHANGELOG.md
README.md
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

Release 1.0.0 Beta 1

---

ATTNSDKFramework.podspec
CHANGELOG.md
README.md
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

This reverts commit 43230768fc66c2e5179c5cf702c04bafaf5f5341.

Revert "Revert "Release 1.0.0 Beta 1 (#102)" (#104)"

---

ATTNSDKFramework.podspec
CHANGELOG.md
README.md
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

- Bumped version to 1.0.0-beta.2
- Updated CHANGELOG.md

Release 1.0.0-beta2

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/ui.yml
Sources/Public/SDK/ATTNSDK.swift

[Jira Link](https://attentivemobile.atlassian.net/browse/APP-3091)
- Removed swift-migration branch from ci files
- Changed SDK config log to public

[APP-3091] Create documentation for developers that details how to set up the apps locally, test, and release

---

ATTNSDKFramework.podspec
CHANGELOG.md
README.md
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

Release 1.0.0 Beta 3

---

Example/Base.lproj/Main.storyboard
Example/Example/ProductViewController.m
Sources/API/ATTNEventRequest.swift
Sources/Helpers/Extension/ATTNAddToCartEvent+Extension.swift
Sources/Helpers/Extension/ATTNProductViewEvent+Extension.swift
Sources/Public/Events/ATTNAddToCartEvent.swift
Sources/Public/Events/ATTNDeeplinkHandling.swift
Sources/Public/Events/ATTNProductViewEvent.swift
Sources/URLProviders/ATTNEventURLProvider.swift
Tests/TestCases/ATTNAddToCartEventTests.swift
Tests/TestCases/ATTNProductViewEventTests.swift
attentive-ios-sdk.xcodeproj/project.pbxproj

[Jira Link](https://attentivemobile.atlassian.net/browse/APP-3103)
Add capability to include deeplink to the following events
- ATTNProductViewEvent
- ATTNAddToCartEvent

[APP-3103] Add request url to SDK framework

---

ATTNSDKFramework.podspec
CHANGELOG.md
README.md
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

Release 1.0.0-beta 4

---

ATTNSDKFramework.podspec
CHANGELOG.md
README.md
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

Release 1.0.0 Beta 5

---

ATTNSDKFramework.podspec
CHANGELOG.md
README.md
Sources/ATTNConstants.swift
attentive-ios-sdk.podspec

- Updated changelog
- Bumped version to 1.0.0

Release 1.0.0

---

Example/CreativeUITest/CreativeUITest.swift
Example/CreativeUITest/Pages/CreativePage.swift
Example/Example.xcodeproj/project.pbxproj
Example/Podfile
ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj
Sources/Public/SDK/ATTNSDK.swift
Tests/TestCases/ATTNSDKTests.swift
attentive-ios-sdk.xcworkspace/xcshareddata/swiftpm/Package.resolved

- Added missing static variable to maintain one single instance of Creative
- Updated UI Test cases
- Fixed min iOS version in the Examples App
- Corrected Example Swift Package Dependency version

Multiple Creative Instances

---

Sources/ATTNWebViewHandling.swift

[Jira Link](https://attentivemobile.atlassian.net/browse/NATV-28)
Allow full-screen creatives to receive all user interactions. 
https://github.com/user-attachments/assets/b7ff9cf3-c417-43fc-83e4-69fc8c4b7acd

Expand web view hit area to make sure full screen creatives receive all user interactions 

---

ATTNSDKFramework.podspec
Sources/ATTNWebViewHandling.swift
attentive-ios-sdk.podspec

[Jira Link](https://attentivemobile.atlassian.net/browse/NATV-28)
Red rectangle is the interactive area border which is aligning perfectly with the 76ers creative.

Adelag 1.0.2 beta.10

---

README.md

Rewrite README for clarity

---

Bonni/AttentiveExample/AppDelegate.swift
Bonni/AttentiveExample/SettingsViewController.swift
Bonni/Bonni.xcodeproj/xcshareddata/xcschemes/AttentiveExample.xcscheme
Sources/API/ATTNAPI.swift
Sources/API/ATTNAPIProtocol.swift
Sources/ATTNLaunchManager.swift
Sources/Public/SDK/ATTNSDK.swift
Tests/Doubles/Spies/ATTNAPISpy.swift
attentive-ios-sdk.xcodeproj/project.pbxproj

[Jira Link](https://attentivemobile.atlassian.net/browse/NATV-44)

Natv 44: register app events for app launches

---

Bonni/ATTNNotificationService/Info.plist
Bonni/ATTNNotificationService/NotificationService.swift
Bonni/AttentiveExample/AppDelegate.swift
Bonni/Bonni.xcodeproj/project.pbxproj
Sources/Public/SDK/ATTNSDK.swift

[Jira Link](https://attentivemobile.atlassian.net/browse/NATV-41)
Added image support for push (thumbnail and expanded state for images)

natv41 - push image support

---

README.md
Sources/ATTNConstants.swift
Sources/Public/SDK/ATTNSDK.swift
attentive-ios-sdk.podspec

[Jira Link](https://attentivemobile.atlassian.net/browse/NATV-95)
1) Added completion handler to registerForPushNotifications
2) Removed excess event tracking during init

NATV-95 Add completion handler to registerForPushNotifications
